# Generated by Django 4.0 on 2021-12-12 22:23

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_answer_attempt_profile_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='unanswered',
            field=models.CharField(help_text='A list of integer ids of all unanswered questions', max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
